<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-I4HI49V" failures="2" tests="19" name="org.example.TestRunner.Runners" time="256.159" errors="2" timestamp="2022-11-15T20:34:26 EET" skipped="0">
  <testcase classname="org.example.TestRunner.Runners" name="runScenario" time="7.633">
    <failure message="This is First Url expected [ https://demo.nopcommerce.com/nokia-lumia-1020] but found [https://demo.nopcommerce.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: This is First Url expected [ https://demo.nopcommerce.com/nokia-lumia-1020] but found [https://demo.nopcommerce.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.example.stepDefinations.D06_homeSlidersStepDef.navigateToThePageOfFirstSlider(D06_homeSlidersStepDef.java:25)
at ✽.navigate to the page of first slider(file:///D:/palo/New%20folder%20(2)/Ecomerce/src/main/resources/Features/F006_homeSliders.feature:5)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="org.example.TestRunner.Runners" name="runScenario" time="13.553"/>
  <system-out/>
  <testcase classname="org.example.TestRunner.Runners" name="runScenario" time="10.356"/>
  <system-out/>
  <testcase classname="org.example.TestRunner.Runners" name="runScenario" time="8.931"/>
  <system-out/>
  <testcase classname="org.example.TestRunner.Runners" name="runScenario" time="34.167">
    <error message="target frame detached
  (failed to check if window was closed: disconnected: unable to connect to renderer)
  (Session info: chrome=107.0.5304.107)
Build info: version: &#039;4.6.0&#039;, revision: &#039;79f1c02ae20&#039;
System info: os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;19&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [564b4005e71049d463446257f3c5bbb0, findElement {using=xpath, value=//div[@class=&quot;result&quot;]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 107.0.5304.107, chrome: {chromedriverVersion: 107.0.5304.62 (1eec40d3a576..., userDataDir: C:\Users\FIXSTO~1\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:65391}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:65391/devtoo..., se:cdpVersion: 107.0.5304.107, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 564b4005e71049d463446257f3c5bbb0" type="org.openqa.selenium.WebDriverException">
      <![CDATA[org.openqa.selenium.WebDriverException: target frame detached
  (failed to check if window was closed: disconnected: unable to connect to renderer)
  (Session info: chrome=107.0.5304.107)
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '19'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [564b4005e71049d463446257f3c5bbb0, findElement {using=xpath, value=//div[@class="result"]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 107.0.5304.107, chrome: {chromedriverVersion: 107.0.5304.62 (1eec40d3a576..., userDataDir: C:\Users\FIXSTO~1\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:65391}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:65391/devtoo..., se:cdpVersion: 107.0.5304.107, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 564b4005e71049d463446257f3c5bbb0
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:541)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:162)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:60)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:365)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:357)
at org.example.Pages.P01_registerPom.sucssesMasege(P01_registerPom.java:84)
at org.example.stepDefinations.D1_registerStepDefinations.SuccessMessage(D1_registerStepDefinations.java:59)
at ✽.success message is displayed(file:///D:/palo/New%20folder%20(2)/Ecomerce/src/main/resources/Features/F001_Register.feature:13)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="org.example.TestRunner.Runners" name="runScenario" time="19.199"/>
  <system-out/>
  <testcase classname="org.example.TestRunner.Runners" name="runScenario" time="9.447"/>
  <system-out/>
  <testcase classname="org.example.TestRunner.Runners" name="runScenario" time="9.646"/>
  <system-out/>
  <testcase classname="org.example.TestRunner.Runners" name="runScenario" time="9.892"/>
  <system-out/>
  <testcase classname="org.example.TestRunner.Runners" name="runScenario" time="10.555"/>
  <system-out/>
  <testcase classname="org.example.TestRunner.Runners" name="runScenario" time="9.609"/>
  <system-out/>
  <testcase classname="org.example.TestRunner.Runners" name="runScenario" time="18.590"/>
  <system-out/>
  <testcase classname="org.example.TestRunner.Runners" name="runScenario" time="9.652"/>
  <system-out/>
  <testcase classname="org.example.TestRunner.Runners" name="runScenario" time="12.828"/>
  <system-out/>
  <testcase classname="org.example.TestRunner.Runners" name="runScenario" time="18.913"/>
  <system-out/>
  <testcase classname="org.example.TestRunner.Runners" name="runScenario" time="8.287">
    <error message="Index 1 out of bounds for length 1" type="java.lang.IndexOutOfBoundsException">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:385)
at java.base/java.util.ArrayList.get(ArrayList.java:427)
at org.example.Pages.P04_homePagePom.assertRss(P04_homePagePom.java:126)
at org.example.stepDefinations.D07_followUsStepDef.rssIsOpenedInANewTab(D07_followUsStepDef.java:49)
at ✽.rss is Opened in a new tab(file:///D:/palo/New%20folder%20(2)/Ecomerce/src/main/resources/Features/F007_followUs.feature:15)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="org.example.TestRunner.Runners" name="runScenario" time="13.283"/>
  <system-out/>
  <testcase classname="org.example.TestRunner.Runners" name="runScenario" time="7.872">
    <failure message="This is second Url expected [https://demo.nopcommerce.com/iphone-6] but found [https://demo.nopcommerce.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: This is second Url expected [https://demo.nopcommerce.com/iphone-6] but found [https://demo.nopcommerce.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.example.stepDefinations.D06_homeSlidersStepDef.navigateToThePageOfSecondSlider(D06_homeSlidersStepDef.java:39)
at ✽.navigate to the page of second slider(file:///D:/palo/New%20folder%20(2)/Ecomerce/src/main/resources/Features/F006_homeSliders.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="org.example.TestRunner.Runners" name="runScenario" time="23.746"/>
  <system-out/>
</testsuite> <!-- org.example.TestRunner.Runners -->
